# 06项目只是一个功能测试项目
# 测试 ribbon hystrix的功能
# 两个工具测试完之后，这个项目会删除
spring:
  application:
    name: hystrix
server:
  port: 3001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

ribbon:
  #单台服务器的重试次数
  MaxAutoRetries: 1
  #更换服务器次数
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  #OkToRetryOnAllOperations 是否对所有类型请求都重试，默认只对GET重试
  #ConnectTimeout 建立连接等待等待超时时间（不能再yml中配置，需要些Java代码进行配置）
  #ReadTimeout 连接已建立并已发送请求，等待接收响应的超时时间（不能再yml中配置，需要些Java代码进行配置）

#hystrix等待超时后, 会执行降级代码, 快速向客户端返回降级结果, 默认超时时间是1000毫秒
#为了测试 hystrix 降级，我们把 hystrix 等待超时设置得非常小（500毫秒）
#此设置一般应大于 ribbon 的重试超时时长，例如 10 秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
#hystrix中的一些属性配置
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds
#请求超时时间（单位：毫秒），超时后触发失败降级
#hystrix.command.default.circuitBreaker.requestVolumeThreshold
#10秒内请求数量，默认20，如果没有达到该数量，即使请求全部失败，也不会触发断路器打开
#hystrix.command.default.circuitBreaker.errorThresholdPercentage
#失败请求百分比，达到该比例则触发断路器打开
#hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds
#断路器打开多长时间后，再次允许尝试访问（半开），仍失败则继续保持打开状态，如成功访问则关闭断路器，默认 5000


#暴露 hystrix.stream 监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream