#向注册中心注册的服务ID
spring:
  application:
    name: user-service
  #默认配置中心配置优先级高,配置中心配置会覆盖客户端的所有配置,包括命令行参数配置
  cloud:
    config:
      override-none: true

#端口号
server:
  port: 8101

#自定义配置属性
#测试用的用户数据
#sp.user-service.users=[{},{},{}]
sp:
  user-service:
    users: "[{'id':7, 'username':'abc','password':'123'},
             {'id':8, 'username':'def','password':'456'},
             {'id':9, 'username':'ghi','password':'789'},
             {'id':99,'username':'aaa','password':'111'}]"

#sp:
  #user-service:
    #users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},
             #{\"id\":8, \"username\":\"def\",\"password\":\"456\"},
             #{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

#暴露refresh端点
management:
  endpoints:
    web:
      exposure:
        include: refresh